# Generated by Django 4.0.6 on 2022-07-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='physical_serial_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
