# Generated by Django 4.0.6 on 2022-07-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inventoryitem_physical_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='home_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
