# Generated by Django 4.0.6 on 2022-07-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_installation_home_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='items_used',
            field=models.ManyToManyField(related_name='installations', to='main.inventoryitem'),
        ),
    ]
