# Generated by Django 4.0.6 on 2022-07-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_installation_items_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='items_used',
            field=models.ManyToManyField(to='main.inventoryitem'),
        ),
    ]
