# Generated by Django 4.0.6 on 2022-07-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_installation_items_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='depreciated_status',
            field=models.BooleanField(default=False),
        ),
    ]
