# Generated by Django 4.0.6 on 2022-07-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_inventoryitem_depreciated_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(blank=True, max_length=10, null=True)),
                ('reg_key', models.CharField(blank=True, max_length=15, null=True)),
                ('ph_serial_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='holder',
            name='holder_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='installation',
            name='home_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='reg_key',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='home_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='physical_serial_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='registration_key',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(blank=True, choices=[('Installed', 'Installed'), ('In hands of', 'In hands of'), ('Warehouse', 'Warehouse')], default='Warehouse', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='itemtitle',
            name='item_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='techuser',
            name='email',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='techuser',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='techuser',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
