# Generated by Django 4.0.6 on 2022-07-24 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alarm_alter_holder_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='error_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.techuser'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='where',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='home_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='installed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.holder'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.itemtype'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('Installed', 'Installed'), ('In hands of', 'In hands of'), ('Warehouse', 'Warehouse')], default='Warehouse', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.itemtitle'),
        ),
    ]
