# Generated by Django 4.0.6 on 2022-07-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alarm_error_to_alter_alarm_where_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='item_in_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.inventoryitem'),
        ),
    ]
