# Generated by Django 4.0.6 on 2022-07-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alarm_item_in_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
