# Generated by Django 4.0.6 on 2022-07-25 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alarm_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='holder_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.techuser'),
        ),
    ]
