# Generated by Django 4.0.6 on 2022-08-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_holder_holder_techuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='uninstalled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='imei_1',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='imei_2',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='phone_number_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
