# Generated by Django 4.0.6 on 2022-08-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_installation_uninstalled_inventoryitem_imei_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='reg_key',
        ),
        migrations.AddField(
            model_name='installation',
            name='distance_in_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
