# Generated by Django 4.0.6 on 2022-08-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_itemsonhand_date_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsonhand',
            name='related_file_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
