# Generated by Django 4.0.6 on 2022-08-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_itemsonhand_related_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsonhand',
            name='date_registered',
        ),
    ]
